# .goreleaser.yml
# Build customization
builds:
  - main: waflyctl.go
    binary: waflyctl
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
# Archive customization
archive:
  format: tar.gz
  files:
    - waflyctl.toml
    - config_examples/waflyctl.fastly_soc_example.toml 
    - README.md
# HomeBrew Tap generation
brew:
  github:
    owner: fastly
    name: homebrew-tap
  folder: Formula
  homepage:  https://github.com/fastly/waflyctl
  description: Allows you to provision a Fastly waf object with pre-determine rules, OWASP config, response, and logging endpoints. Also manage rules, and their status.
  test: |
    system "#{bin}/waflyctl"
